name: Deploy Automatico eduaibar

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar al VPS y actualizar Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_VPS }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/mi-web-segura
            git pull origin master
            docker compose up -d --build
